---
#
# Packages for apt-get and others to install, remove, etc.
#

# key packages possibly missing for some reason from the image
pkgs_to_install:
  - man-db
  - aptitude
  - udisks2

# frequency at which ntpdate should be run, can be hourly, weekly, monthly
ntpdate_freq: hourly
