#
# wpa network settings
#
# this defaults to obtaining the values from the command line, using
# -e wpa_ssid=SSID -e wpa_passkey=WPAPASS
#
# wpa_keymgmt can be set as well, defaults to WPA-PSK (see template) 
#
wpa:
  ssid: "{{ wpa_ssid|default(none) }}"
  passkey: "{{ wpa_passkey|default(none) }}"
  keymgmt: "{{ wpa_keymgmt|default(none) }}"
